executor: slurm
jobs: 100

default-resources:
  slurm_partition: "workq"
  slurm_account: "mnaji"
  mem: 12GB
  time: 8:00:00
set-threads:
    bwamap: 24
    remove_dup: 24
    indexing_xg: 5
    giraffe_autoindex: 1
    giraffe_mapping: 32
    giraffe_chunk: 1
    giraffe_pack: 3
    manta_comp: 8
    paragraph_genotypeSV: 7
    graphtyper_genotype_sv: 7
    indexing_xg_breed: 5
    giraffe_autoindex_breed: 1
    giraffe_mapping_breed: 10
    giraffe_mapping_stats_breed: 7
    giraffe_chunk_breed: 1
    giraffe_pack_breed: 3
set-resources:
    bwamap:
      mem: 64GB
    remove_dup:
      mem: 64GB
    indexing_xg:
      mem: 100GB
    giraffe_autoindex:
      mem: 100GB
    giraffe_mapping:
      mem: 40GB
    giraffe_chunk:
      mem: 30GB
    giraffe_pack:
      mem: 15GB
    manta_comp:
      mem: 30GB
    paragraph_genotypeSV:
      mem: 21GB
    graphtyper_genotype_sv:
      mem: 12GB
    indexing_xg_breed:
      mem: 100GB
    giraffe_autoindex_breed:
      mem: 100GB
    giraffe_mapping_breed:
      mem: 40GB
    giraffe_mapping_stats_breed:
      mem: 40GB
    giraffe_chunk_breed:
      mem: 30GB
    giraffe_pack_breed:
      mem: 15GB



