samples1: /work/project/CASCAD/mnaji/sm_folder/workflow/samples_dairy1.tsv            #samples to be aligned to SV panel
samples2: /work/project/CASCAD/mnaji/sm_folder/workflow/samples_dairy2.tsv            #replace HOLFRAM007241082273 by HOLFRAM008550173894 for validation individual
samples3: /work/project/CASCAD/mnaji/sm_folder/workflow/samples_dairy3.tsv            # replace validation individual to HOLFRAM004460056593 & HOLFRAM008069306607 (French parents)
samples4: /work/project/CASCAD/mnaji/sm_folder/workflow/samples_dairy4.tsv            # replace validation individual to HOLFRAM004460056593 & HOLFRAM008069306607 (French parents) - for panel using all 14 breeds

ref:
  name: BT
  # Path to the reference genome
  genome: "/work/project/G2BSeq/Sequences/RUN7/REF/ARS-UCD1.2_Btau5.0.1Y.fa"
  bed: "/work/project/CASCAD/mnaji/sm_folder/resources/ars_pos.bed"
  known_sites: "/work/project/CASCAD/mnaji/sm_folder/resources/ARS1.2PlusY_BQSR.vcf.gz"
  autX: "/work/project/CASCAD/mnaji/sm_folder/resources/autX.txt"

lr_dir: "/work/project/CASCAD/mnaji/sm_folder/data1"

workdir: "/work/project/CASCAD/mnaji/sm_folder/results"

tmpdir: "/work/project/CASCAD/mnaji/sm_folder/results/tmp"

